#       
add_newline = true

#FORMATING
right_format = """
$cmd_duration$time[┘](fg:#FF5955)
"""
format = """
[┌](fg:#FF5955)$shell$jobs[─────](fg:#FF5955)$all
[│](fg:#FF5955) 
[└─](fg:#FF5955)[](fg:#FF5955)[$hostname ](bg:#FF5955 fg:#FF5955)[](fg:#FF5955) """

[line_break]
disabled = true

[character]
#disabled = true
#style = "bg:#FF5955 fg:#FFFFFF"
success_symbol = ""
error_symbol = ""
vicmd_symbol = ""

[directory]
disabled = false
style = "bg:#FF5955 fg:#FFFFFF"
format = "[](fg:#FF5955)[$read_only ]($style)[$path ]($style)[](fg:#FF5955)"
read_only=" "
truncate_to_repo = false
fish_style_pwd_dir_length = 1

[hostname]
disabled = false
style = "bg:#FF5955 fg:#FFFFFF"
format = "[ $ssh_symbol$hostname]($style)"
ssh_only = false
trim_at = ".local"

[username]
disabled = true
style_user = "bg:#FF5955 fg:#FFFFFF"
style_root = "bg:#FF5955 fg:#fb4934"
format = "[ $user]($style)"
show_always = true

[localip]
disabled = false
ssh_only = true
format = "[](fg:#FF5955)[$localipv4](bg:#FF5955 fg:#FFFFFF)[](fg:#FF5955)"

[shell]
fish_indicator = ""
powershell_indicator = "_"
unknown_indicator = "mystery shell"
style = "bg:#FF5955 fg:#FFFFFF"
format = "[](fg:#FF5955)[$indicator](bg:#FF5955 fg:#FFFFFF)[](fg:#FF5955)"
disabled = false

[cmd_duration]
disabled = false
style = "bg:#FF5955 fg:#FFFFFF"
format = "[](fg:#FF5955)[ ]($style)[$duration]($style)[](fg:#FF5955)"
#min_time_to_notify = "59"

[jobs]
symbol = "+"
format = "[](fg:#FF5955)[$symbol$number](bg:#FF5955 fg:#FFFFFF)[](fg:#FF5955)"
number_threshold = 2
symbol_threshold = 1

[time]
disabled = false
style = "bg:#FF5955 fg:#FFFFFF"
format = "[](fg:#FF5955)[ ]($style)[$time]($style)[](fg:#FF5955)"
#time_format = "%T"
#utc_time_offset = "1"
#time_range = "00:00:00-06:00:00"

[memory_usage]
disabled = true
style = "bg:#FF5955 fg:#FFFFFF"
format = "[](fg:#FF5955)[$symbol]($style)[${ram}( | ${swap}) ]($style)[](fg:#FF5955)"
symbol = "  "
threshold = 0

[battery]
disabled = true
style = "bg:#FF5955 fg:#FFFFFF"
unknown_symbol = "  "
empty_symbol = "  "
discharging_symbol = "  "
charging_symbol = "  "
full_symbol = "  "
        [[battery.display]]
        threshold = 10
        style = "bold fg:#fb4934"

        [[battery.display]]
        threshold = 30
        style = "fg:#FF5955"

        [[battery.display]]
        threshold = 50
        style = "fg:#fabd2f"

        

# VCS
[git_branch]
#disabled = true
symbol = " "
style = "bg:#FF5955 fg:#FFFFFF"
format = "[](fg:#FF5955)[$symbol$branch]($style)[](fg:#FF5955)"

[git_commit]
#disabled = true
style = "bg:#FF5955 fg:#FFFFFF"
format = "[](fg:#FF5955)[ ﰖ $hash]($style)[](fg:$style) "

[git_state]
#disabled = true
style = "bg:#FF5955 fg:#FFFFFF"
format = "[](fg:#FF5955)[State:($state( $progress_current/$progress_total))]($style)[](fg:$style) "
am = "APPLYING-MAILBOX"
am_or_rebase = "APPLYING-MAILBOX/REBASE"

[git_status]
#disabled = true
style = "bg:#FF5955 fg:#FFFFFF"
format = "($conflicted$staged$modified$renamed$deleted$untracked$stashed$ahead_behind)"
conflicted = "[](fg:#FF5955)[Conflicted:${count}](bg:#FF5955)[](fg:#FF5955)"
staged = "[](fg:#FF5955)[Staged:${count}](bg:#FF5955)[](fg:#FF5955)"
modified = "[](fg:#FF5955)[Modified:${count}](bg:#FF5955)[](fg:#FF5955)"
renamed = "[](fg:#FF5955)[Renamed:${count}](bg:#FF5955)[](fg:#FF5955)"
deleted = "[](fg:#FF5955)[Deleted:${count}](bg:#FF5955)[](fg:#FF5955)"
untracked = "[](fg:#FF5955)[Untracked:${count}](bg:#FF5955)[](fg:#FF5955)"
stashed = "[](fg:#FF5955)[Stashed:${count}](bg:#FF5955)[](fg:#FF5955)"
ahead = "[](fg:#FF5955)[Ahead:${count}](bg:#FF5955)[](fg:#FF5955)"
behind = "[](fg:#FF5955)[Behind:${count}](bg:#FF5955)[](fg:#FF5955)"
diverged = "[](fg:#FF5955)[Diverged:${count}נּ](bg:#FF5955)[ Ahead:${ahead_count}][ Behind:${behind_count}][](fg:#FF5955)"

[shlvl]
#disabled = true
disabled = false
style = "bg:#FF5955 fg:#FFFFFF"
format = "($style)"
symbol = " "

[env_var]
#disabled = true
style = "bg:#FF5955 fg:#FFFFFF"
format = " gambling with [$env_value]($style)"
variable = "GAMBLE_TEST_COMMAND"

[aws]
disabled = false
style = "bg:#FF5955 fg:#FFFFFF"
format = '[](fg:#FF5955)[ $symbol($profile )(\($region\) )(\[$duration\] )]($style)[](fg:#FF5955)'
symbol = " "

[conda]
#disabled = true
style = "bg:#FF5955 fg:#FFFFFF"
format = "($style)"
symbol = " "

[dart]
#disabled = true
style = "bg:#FF5955 fg:#FFFFFF"
format = "($style)"
symbol = " "

[elixir]
#disabled = true
style = "bg:#FF5955 fg:#FFFFFF"
format = "($style)"
symbol = " "

[elm]
#disabled = true
style = "bg:#FF5955 fg:#FFFFFF"
format = "($style)"
symbol = " "

[golang]
#disabled = true
style = "bg:#FF5955 fg:#FFFFFF"
format = "($style)"
symbol = " "

[java]
#disabled = true
style = "bg:#FF5955 fg:#FFFFFF"
format = "($style)"
symbol = " "

[nix_shell]
#disabled = true
style = "bg:#FF5955 fg:#FFFFFF"
format = "($style)"
symbol = " "

[nodejs]
#disabled = true
style = "bg:#FF5955 fg:#FFFFFF"
format = "($style)[](fg:#FF5955)[$symbol$version]($style)[](fg:#FF5955)"
symbol = " "

[package]
#disabled = true
style = "bg:#FF5955 fg:#FFFFFF"
format = "($style)[](fg:#FF5955)[$symbol$version]($style)[](fg:#FF5955)"

[php]
#disabled = true
style = "bg:#FF5955 fg:#FFFFFF"
format = "($style)"
symbol = " "

[python]
#disabled = true
style = "bg:#FF5955 fg:#FFFFFF"
format = "($style)[](fg:#FF5955)[${symbol}${pyenv_prefix}${version}($virtualenv)]($style)[](fg:#FF5955)"
symbol = " "

[lua]
#disabled = true
style = "bg:#FF5955 fg:#FFFFFF"
format = "($style)[](fg:#FF5955)[${symbol}${version}]($style)[](fg:#FF5955)"
symbol = " "

[ruby]
#disabled = true
style = "bg:#FF5955 fg:#FFFFFF"
format = "($style)"
symbol = " "

[rust]
#disabled = true
style = "bg:#FF5955 fg:#FFFFFF"
format = "($style)"
symbol = "  "
